schema_version = 1
id = "qbe"
name = "QBE"
version = "0.1.0"
description = "QBE IL language support for Zed"
authors = ["thejunt"]
repository = "https://github.com/runt-lang/qbe-zed"

[grammars.qbe]
repository = "https://github.com/runt-lang/qbe-treesitter.git"
rev = "31f89e880a66a62d5e9ae4de9634a3ab0e3383b6"

[language_servers.qbe-lsp]
name = "qbe-lsp"
languages = ["QBE"]
