name = "QBE"
grammar = "qbe"
path_suffixes = ["ssa", "qbe"]
line_comments = ["# "]
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
]
word_characters = ["_", "."]
